train_json_path: '/content/drive/MyDrive/Colab Notebooks/Locomotion/Data/train_data.json'
test_json_path: '/content/drive/MyDrive/Colab Notebooks/Locomotion/Data/test_data.json'
image_folder: '/content/drive/MyDrive/Colab Notebooks/Locomotion/Data/images'
audio_folder: '/content/drive/MyDrive/Colab Notebooks/Locomotion/Data/audios'
output_dir: '/content/drive/MyDrive/Colab Notebooks/Locomotion/Trained'
device: cuda
wandb_project: locomotion-test